#pragma once

#include "../Utils/Zen_MemoryUtils.h"

namespace Zen
{
    // TODO: I need to rethink the lifetime management of objects generated by this class.
    // I know that it's not used externally, but this is a gun sitting with the safety off
    // Right now it depends on the end user knowing that they need to call ~T()
    // and the associated memory return function of choice

    class TypelessComponentFactory
    {
    public:
        template <typename ComponentType>
        static consteval TypelessComponentFactory GetFactory()
        {
            return TypelessComponentFactory([](void* p_address) -> void* {
                return static_cast<void*>(MemoryUtils::PlacementNew<ComponentType>(p_address));
            });
        }

        constexpr void* MakeInPlace(void* p_address) const { return m_makeImpl(p_address); }

    private:
        using MakeFunctionType = void* (*)(void*);

        TypelessComponentFactory() = delete;
        consteval TypelessComponentFactory(MakeFunctionType const& p_makeImpl)
            : m_makeImpl(p_makeImpl)
        {}

    private:
        MakeFunctionType m_makeImpl;
    };
} // namespace Zen