#pragma once

#include "../Utils/Zen_ConceptUtils.h"
#include "../Utils/Zen_MemoryUtils.h"

namespace Zen
{
    // TODO: I need to rethink the lifetime management of objects generated by this class.
    // I know that it's not used externally, but this is a gun sitting with the safety off
    // Right now it depends on the end user knowing that they need to call ~T()
    // and the associated memory return function of choice

    // I've also haphazardly added a generic constructor, which is dangerous because
    // it leaves m_makeImpl as nullptr. Technically it's for error cases but still..

    class TypelessComponentFactory
    {
    public:
        template <typename ComponentType>
        requires(ConceptUtils::IsPureType<ComponentType>)
        static consteval TypelessComponentFactory GetFactory()
        {
            return TypelessComponentFactory(
              [](void* /*p_address*/) -> void* {
                  return nullptr;
                  // return static_cast<void*>(
                  //   MemoryUtils::PlacementNew<ComponentType>(static_cast<ComponentType*>(p_address)));
              },
              [](void* p_component) { static_cast<ComponentType*>(p_component)->~ComponentType(); });
        }

        consteval TypelessComponentFactory() = default;

        constexpr void* MakeInPlace(void* p_address) const { return m_makeImpl(p_address); }
        constexpr void Destroy(void* p_component) const { m_destroyImpl(p_component); }

    private:
        using MakeFunctionType = void* (*)(void*);
        using DestroyFunctionType = void (*)(void*);

        consteval TypelessComponentFactory(MakeFunctionType p_makeImpl, DestroyFunctionType p_destroyImpl)
            : m_makeImpl(p_makeImpl)
            , m_destroyImpl(p_destroyImpl)
        {}

    private:
        MakeFunctionType m_makeImpl = nullptr;
        DestroyFunctionType m_destroyImpl = nullptr;
    };
} // namespace Zen